In [50]:
import os
import pandas as pd
import numpy as np

In [51]:
train_data = pd.read_csv("train.csv")
train_data.head()
# feature cleaning
train_data["Age"] = train_data["Age"].fillna(train_data["Age"].mean())
train_data["Fare"] = train_data["Fare"].fillna(train_data["Fare"].mean())

In [52]:
test_data = pd.read_csv("test.csv")
test_data.head()
test_data["Age"] = test_data["Age"].fillna(train_data["Age"].mean())
test_data["Fare"] = test_data["Fare"].fillna(train_data["Fare"].mean())

In [53]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]
rate_women = sum(women)/len(women)

print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095

In [54]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch", "Fare", "Age"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

In [56]:
X_test.isnull().values.any()

False

In [57]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch", "Fare", "Age"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

     Pclass  SibSp  Parch  Sex_female  Sex_male
0         3      1      0           0         1
1         1      1      0           1         0
2         3      0      0           1         0
3         1      1      0           1         0
4         3      0      0           0         1
5         3      0      0           0         1
6         1      0      0           0         1
7         3      3      1           0         1
8         3      0      2           1         0
9         2      1      0           1         0
10        3      1      1           1         0
11        1      0      0           1         0
12        3      0      0           0         1
13        3      1      5           0         1
14        3      0      0           1         0
15        2      0      0           1         0
16        3      4      1           0         1
17        2      0      0           0         1
18        3      1      0           1         0
19        3      0      0           1         0
20        2      0      0           0         1
21        2      0      0           0         1
22        3      0      0           1         0
23        1      0      0           0         1
24        3      3      1           1         0
25        3      1      5           1         0
26        3      0      0           0         1
27        1      3      2           0         1
28        3      0      0           1         0
29        3      0      0           0         1
..      ...    ...    ...         ...       ...
861       2      1      0           0         1
862       1      0      0           1         0
863       3      8      2           1         0
864       2      0      0           0         1
865       2      0      0           1         0
866       2      1      0           1         0
867       1      0      0           0         1
868       3      0      0           0         1
869       3      1      1           0         1
870       3      0      0           0         1
871       1      1      1           1         0
872       1      0      0           0         1
873       3      0      0           0         1
874       2      1      0           1         0
875       3      0      0           1         0
876       3      0      0           0         1
877       3      0      0           0         1
878       3      0      0           0         1
879       1      0      1           1         0
880       2      0      1           1         0
881       3      0      0           0         1
882       3      0      0           1         0
883       2      0      0           0         1
884       3      0      0           0         1
885       3      0      5           1         0
886       2      0      0           0         1
887       1      0      0           1         0
888       3      1      2           1         0
889       1      0      0           0         1
890       3      0      0           0         1

[891 rows x 5 columns]